---
info:
  title: R7insight Analytic Packs
  description: Analytics Pack for InsightOps
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/r7insight_analytic_packs
  x-cortex-tag: r7insight-analytic-packs
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: insightidr
openapi: 3.0.1
servers:
- url: "/"
